// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SteamGamesWeAllCanPlayWASM.Data;

#nullable disable

namespace SteamGamesWeAllCanPlayWASM.Shared.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220110152650_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("SteamGamesWeAllCanPlayWASM.Shared.Models.MPlayerSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AccountCreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarFullUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarMediumUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<uint>("CityCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommentPermission")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastLoggedOffDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MPlayerSummaryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nickname")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayingGameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayingGameName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayingGameServerIP")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryGroupId")
                        .HasColumnType("TEXT");

                    b.Property<uint>("ProfileState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfileUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileVisibility")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RealName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StateCode")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("SteamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MPlayerSummaryId");

                    b.ToTable("PlayerSummaries");
                });

            modelBuilder.Entity("SteamGamesWeAllCanPlayWASM.Shared.Models.MUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SteamGamesWeAllCanPlayWASM.Shared.Models.MPlayerSummary", b =>
                {
                    b.HasOne("SteamGamesWeAllCanPlayWASM.Shared.Models.MPlayerSummary", null)
                        .WithMany("Friends")
                        .HasForeignKey("MPlayerSummaryId");
                });

            modelBuilder.Entity("SteamGamesWeAllCanPlayWASM.Shared.Models.MPlayerSummary", b =>
                {
                    b.Navigation("Friends");
                });
#pragma warning restore 612, 618
        }
    }
}
